### ISSUE TITLE
 builtin: Index Colorschemes Error

### ISSUE THREAD

**Issue by ArseniD** [iamcco/coc-vimlsp#2]
Hi,

I got the following error for **vimlsp** module when running **CocInfo**.
Could you please elucidate why it's happen or how I can fix that?

## Output channel: vimlsp

```
[Error  - 5:12:52 PM] builtin: Index Colorschemes Error: ["/var/home/adudko/.config/coc/extensions/node_modules/coc-snippets/colors/*.vim","/var/home/adudko/.vim/colors/*.vim","/var/home/adudko/.vim/plugged/coc.nvim/colors/*.vim","/var/home/adudko/.vim/plugged/indentLine/colors/*.vim","/var/home/adudko/.vim/plugged/vim-airline/colors/*.vim","/var/home/adudko/.vim/plugged/vim-tmux-navigator/colors/*.vim","/var/home/adudko/.vim/plugged/vimux/colors/*.vim","/var/home/adudko/.vim/plugged/tmuxline.vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-surround/colors/*.vim","/var/home/adudko/.vim/plugged/vim-easymotion/colors/*.vim","/var/home/adudko/.vim/plugged/vim-expand-region/colors/*.vim","/var/home/adudko/.vim/plugged/vim-visual-multi/colors/*.vim","/var/home/adudko/.vim/plugged/vim-snippets/colors/*.vim","/var/home/adudko/.vim/plugged/vim-commentary/colors/*.vim","/var/home/adudko/.vim/plugged/vim-repeat/colors/*.vim","/var/home/adudko/.vim/plugged/vinarise.vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-obsession/colors/*.vim","/var/home/adudko/.vim/plugged/csv.vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-eunuch/colors/*.vim","/var/home/adudko/.vim/plugged/vim-easy-align/colors/*.vim","/var/home/adudko/.vim/plugged/emmet-vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-git/colors/*.vim","/var/home/adudko/.vim/plugged/vim-fugitive/colors/*.vim","/var/home/adudko/.vim/plugged/vim-gitgutter/colors/*.vim","/var/home/adudko/.vim/plugged/gist-vim/colors/*.vim","/var/home/adudko/.vim/plugged/nerdtree-git-plugin/colors/*.vim","/var/home/adudko/.vim/plugged/rainbow_parentheses.vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-json/colors/*.vim","/var/home/adudko/.vim/plugged/moby/contrib/syntax/vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-better-whitespace/colors/*.vim","/var/home/adudko/.vim/plugged/conoline.vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-javascript/colors/*.vim","/var/home/adudko/.vim/plugged/ale/colors/*.vim","/var/home/adudko/.vim/plugged/tabular/colors/*.vim","/var/home/adudko/.vim/plugged/vim-markdown/colors/*.vim","/var/home/adudko/.vim/plugged/indentpython.vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-indent-object/colors/*.vim","/var/home/adudko/.vim/plugged/python-syntax/colors/*.vim","/var/home/adudko/.vim/plugged/vim-autoformat/colors/*.vim","/var/home/adudko/.vim/plugged/SimpylFold/colors/*.vim","/var/home/adudko/.vim/plugged/vim-ragtag/colors/*.vim","/var/home/adudko/.vim/plugged/vim-gutentags/colors/*.vim","/var/home/adudko/.vim/plugged/ctags/colors/*.vim","/var/home/adudko/.fzf/colors/*.vim","/var/home/adudko/.vim/plugged/fzf.vim/colors/*.vim","/var/home/adudko/.vim/plugged/ctrlp.vim/colors/*.vim","/var/home/adudko/.vim/plugged/incsearch.vim/colors/*.vim","/var/home/adudko/.vim/plugged/incsearch-easymotion.vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-abolish/colors/*.vim","/var/home/adudko/.vim/plugged/vim-startify/colors/*.vim","/var/home/adudko/.vim/plugged/vim-nerdtree-syntax-highlight/colors/*.vim","/var/home/adudko/.vim/plugged/vim-devicons/colors/*.vim","/var/home/adudko/.vim/plugged/FastFold/colors/*.vim","/var/home/adudko/.vim/plugged/vim-colorschemes/colors/*.vim","/var/home/adudko/.vim/plugged/startuptime.vim/colors/*.vim","/var/home/adudko/.vim/plugged/vim-dispatch/colors/*.vim","/var/home/adudko/.vim/plugged/neoterm/colors/*.vim","/usr/share/vim/vimfiles/colors/*.vim","/usr/share/vim/vim81/colors/*.vim","/usr/share/vim/vimfiles/after/colors/*.vim","/var/home/adudko/.fzf/colors/*.vim","/var/home/adudko/.vim/plugged/indentLine/after/colors/*.vim","/var/home/adudko/.vim/plugged/vim-javascript/after/colors/*.vim","/var/home/adudko/.vim/plugged/tabular/after/colors/*.vim","/var/home/adudko/.vim/plugged/vim-markdown/after/colors/*.vim","/var/home/adudko/.vim/plugged/vim-nerdtree-syntax-highlight/after/colors/*.vim","/var/home/adudko/.vim/after/colors/*.vim","\n/usr/share/vim/vim81/colors/*.vim"]
Error => Error: no parsers registered for: "
/usr"
    at parse (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/snapdragon/lib/parser.js:473:15)
    at Parser.parse (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/snapdragon/lib/parser.js:477:24)
    at Snapdragon.parse (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/snapdragon/index.js:122:28)
    at Snapdragon.<anonymous> (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/micromatch/lib/utils.js:47:45)
    at parse (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/micromatch/index.js:739:26)
    at memoize (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.parse (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/micromatch/index.js:745:10)
    at create (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/micromatch/index.js:686:44)
    at /var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/micromatch/index.js:695:16
    at memoize (/var/home/adudko/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/micromatch/index.js:859:13)

```

**Comment by ArseniD** [comment]
I guess the error associated with the last element in the list -  **"\n/usr/share/vim/vim81/colors/*.vim"**

**Comment by iamcco** [comment]
fix, please update and have a try.

**Comment by ArseniD** [comment]
Well done! 
The error has gone.
Thank you very much @iamcco !
