### ISSUE TITLE
Invalid buffer id error messages when using fzf-lua

### ISSUE THREAD

**Issue by shyun3** [iamcco/coc-vimlsp#40]
**Describe the bug**
Calling certain [fzf-lua](https://github.com/ibhagwan/fzf-lua) commands causes error messages such as the following to pop up:
```
[coc.nvim]: Error on BufEnter: request error nvim_buf_get_option - Invalid buffer id: 32
Error
    at ML.request (/home/shyun3/.config/nvim/bundle/coc.nvim/build/index.js:20:34604)
    at ML.getOption (/home/shyun3/.config/nvim/bundle/coc.nvim/build/index.js:20:35234)
    at Object.<anonymous> (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:1648)
    at /home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:5290
    at Object.next (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:5395)
    at /home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:4332
    at new Promise (<anonymous>)
    at Module.l (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:4077)
    at m (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:1531)
    at Object.<anonymous> (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:2094)
```

`:CocInfo` recorded the error as follows:
```
2021-09-25T23:44:26.562 ERROR (pid:5424) [node-client] - request error on "nvim_buf_get_option" [ 'iskeyword' ] Invalid buffer id: 32 Error
    at ML.request (/home/shyun3/.config/nvim/bundle/coc.nvim/build/index.js:20:34604)
    at ML.getOption (/home/shyun3/.config/nvim/bundle/coc.nvim/build/index.js:20:35234)
    at Object.<anonymous> (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:1648)
    at /home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:5290
    at Object.next (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:5395)
    at /home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:4332
    at new Promise (<anonymous>)
    at Module.l (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:4077)
    at m (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:1531)
    at Object.<anonymous> (/home/shyun3/.config/coc/extensions/node_modules/coc-vimlsp/out/index.js:2:2094)
```

**To Reproduce**
1. Open a `.vim` file.
2. Execute `:FzfLua help_tags`. Other `fzf-lua` commands can also trigger the error but this may be the simplest.

**Expected behavior**
No error message to appear.

Using `coc-vimlsp` v0.12.2 reduces the number of such errors but it is still possible to trigger.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS running on Windows 10 WSL2

**Comment by shyun3** [comment]
Fixed by #41
