### ISSUE TITLE
Unhandled 'error' event:  EPERM: operation not permitted

### ISSUE THREAD

**Issue by zoumi** [iamcco/coc-vimlsp#46]
Log:

```
 parser: child_log: Index Workspace Error: d:\programs\vim\**\*.vim
Error => Error: EPERM: operation not permitted, scandir 'C:\Users\zoumi\Application Data'
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, scandir 'C:\Users\zoumi\Cookies'
Emitted 'error' event at:
    at c._handleError (D:\programs\vim\coc\extensions\node_modules\coc-vimlsp\out\scan.js:2:377134)
    at D:\programs\vim\coc\extensions\node_modules\coc-vimlsp\out\scan.js:2:376832
    at worked (D:\programs\vim\coc\extensions\node_modules\coc-vimlsp\out\scan.js:2:382257)
    at D:\programs\vim\coc\extensions\node_modules\coc-vimlsp\out\scan.js:2:376951
    at u (D:\programs\vim\coc\extensions\node_modules\coc-vimlsp\out\scan.js:2:378889)
    at D:\programs\vim\coc\extensions\node_modules\coc-vimlsp\out\scan.js:2:378083
    at fs.js:180:23
    at FSReqCallback.req.oncomplete (fs.js:1026:9) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'scandir',
  path: 'C:\\Users\\zoumi\\Cookies'
}
parser: disconnect
parser: exit: 1, signal: null
parser: close: 1, signal: null
```

**Comment by iamcco** [comment]
Do you open vim file in `C://` directory?

**Comment by iamcco** [comment]
Or some vim file link to `C://xxx`

**Comment by zoumi** [comment]
I have no idea why it scans C://XXX. I'm editing a file under d:\programs\vim\.
If this error doesn't make the lsp server exit unexpectedly, we can ignore it.

**Comment by iamcco** [comment]
Please set `"vimlsp.indexes.runtimepath": false` to test if it's because the vim runtime files in `C://`

**Comment by zoumi** [comment]
Thank you. I will re-open this issue when I can stably reproduce it.
