### ISSUE TITLE
Goto defintion/find reference doesn't work

### ISSUE THREAD

**Issue by eyalk5** [iamcco/coc-vimlsp#9]
Hi,

I am on nvim 0.5.0 and I try to use the plugin.
I get error on every gotodefintion and goto reference I try. 
This is in the log: 
 
```
## Output channel: vimlsp

events.js:298
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:686:16)
    at t._next (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:50:146211)
    at t.__tryOrUnsub (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:35:62808)
    at t.next (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:35:61915)
    at t._next (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:35:60945)
    at t.next (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:35:60616)
    at t._next (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:50:55668)
    at t.next (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:35:60616)
    at t.notifyNext (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:50:45139)
    at t._next (/Users/eyalkarni/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:50:40619)
Emitted 'error' event on process instance at:
    at internal/child_process.js:690:35
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

**Comment by iamcco** [comment]
Can not reproduce.
